### PR TITLE
[6.0] use SymbolKit's unified graph overload grouping

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
- **Explanation**: Use a new implementation for grouping overloads, to address bugs in the existing implementation.
- **Scope**: Bug fix in an experimental feature
- **Issue**: rdar://128624412
- **Original PR**: https://github.com/swiftlang/swift-docc/pull/986
- **Risk**: Low. The change is isolated to the use of an experimental feature, and the behavior has been validated to be the same.
- **Testing**: Automated and manual testing
- **Reviewer**: @d-ronnqvist 

This PR also includes an update to Package.swift to point to the release branches of our dependencies.

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Linux CI should be fixed by https://github.com/swiftlang/swift-docc/pull/998

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by franklinsch — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test Linux

**Comment by QuietMisdreavus** [comment]
```
docc/Tests/SwiftDocCUtilitiesTests/PreviewServer/RequestHandler/FileRequestHandlerTests.swift:152: error: FileRequestHandlerTests.testMalformedURI : XCTAssertEqual failed: ("Optional(401)") is not equal to ("Optional(400)")
```

This reproduces without this change, but not on the main branch. I'm going to open another PR to mask this test out of Linux as well.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
