### PR TITLE
Temporarily avoid using FoundationXML to unblock CI

### PR DESCRIPTION
**Pull request by d-ronnqvist**
Bug/issue #, if applicable: 

## Summary

This works around rdar://138726860 and rdar://139446585 to unblock DocC from building in the CI with the "swift-DEVELOPMENT-SNAPSHOT-2024-10-30-a" toolchain.

## Dependencies

None.

## Testing

Check below that the Linux CI passes.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] Added tests
- [ ] Ran the `./bin/test` script and it succeeded
- [ ] Updated documentation if necessary

### CODE REVIEW

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Review by mayaepps — APPROVED** [review]

**Review by sofiaromorales — APPROVED** [review]

**Review by franklinsch — APPROVED** [review]

**Pull request merged**
