### PR TITLE
Fix https://github.com/swiftlang/swift-docc/issues/1066

### PR DESCRIPTION
**Pull request by icanzilb**
Bug/issue #, if applicable: https://github.com/swiftlang/swift-docc/issues/1066

## Summary

Folds sequential `filter` and `first` into a single `filter(where:)` to prevent the extra step.

## Dependencies

n/a

## Testing

The optimization only takes place when running on Linux with benchmarking enabled. I.e.:

```
DOCC_BENCHMARK=YES [further env variables] ./docc convert [further arguments]
```

There isn't a specific unit test covering the change as the behavior is unchanged.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [n/a] Added tests
- [X] Ran the `./bin/test` script and it succeeded
- [n/a] Updated documentation if necessary

### CODE REVIEW

**Comment by icanzilb** [comment]
@swift-ci Please smoke test

**Review by d-ronnqvist — COMMENTED** [review]
I think this is a fine change for code readability but it doesn't have any performance impact in practice since it's only applies to the lines that takes up 0.1% of the time to compute this peak memory metric on Linux.

Screenshot 2024-10-21 at 12 06 06

If we wanted to address the performance of this code we should avoid splitting all the lines (which is where ~80% of the time is spent) and find the "VmPeak" line in a way that avoids new allocations. 

That said, this metric is only computed once during a full documentation build and doesn't even register in a profile so the performance of this function isn't a problem.

**Review by d-ronnqvist — APPROVED** [review]

**Comment by icanzilb** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
