### PR TITLE
Revert "mask out tests that are failing on Linux (#996)"

### PR DESCRIPTION
**Pull request by anferbui**
Bug/issue #, if applicable: 

## Summary

This reverts commit 3d5851424048dcba763987df157244f8f2e04f12.

This is to revert skipping the tests that were failing on Linux due to a known issue. If CI passes, we can merge this PR. Otherwise, we need to hold off until the fix makes it into the docker build.

This PR 

## Dependencies

N/A

## Testing

Unit tests.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- ~~[ ] Added tests~~ N/A
- [x] Ran the `./bin/test` script and it succeeded
- ~~[ ] Updated documentation if necessary~~ N/A

### CODE REVIEW

**Comment by anferbui** [comment]
@swift-ci please test

**Comment by anferbui** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
