### PR TITLE
add conformance availability data to overloaded declarations

### PR DESCRIPTION
**Pull request by QuietMisdreavus**
Bug/issue #, if applicable: rdar://122589806

## Summary

Currently, the overloaded-declarations feature will save the overloaded symbols' declarations into the other symbols' Render JSON. This works well enough when symbols are overloaded by something that might appear their declarations, like function parameter types. However, overload groups may also be created for symbols with otherwise identical declarations, like with this example:

```swift
public class MyClass<T> {}

extension MyClass where T: Equatable {
    public func myFunc() {}
}

extension MyClass where T: Hashable {
    public func myFunc() {}
}
```

In situations like this, we need to also provide the conformance information in the overloaded declaration list, so that it may be rendered.

## Dependencies

A Swift-DocC-Render PR (not written yet) is required to actually display the conformance information.

## Testing

[This documentation catalog](https://github.com/user-attachments/files/16563803/asdf.docc.zip) contains a symbol graph generated from the above code. Although the associated renderer PR is not available yet, the Render JSON can still be inspected to verify the code is working as intended.

Steps:
1. `DOCC_JSON_PRETTYPRINT=YES swift run docc convert --enable-experimental-overloaded-symbol-presentation path/to/asdf.docc`
2. Open `asdf.docc/.docc-build/data/documentation/conformanceoverloads/myclass/myfunc()-6gquc.json`.
3. Inspect `primaryContentSections[0].declarations[0].otherDeclarations.declarations[0].conformance.constraints` (written as a `jq` filter) to ensure that it says "`T` conforms to `Equatable`." as Render JSON's inline-content data.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [x] Added tests
- [x] Ran the `./bin/test` script and it succeeded
- [ n/a ] Updated documentation if necessary

### CODE REVIEW

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
Note that this Render JSON structure is subject to change, since @hqhhuang might need a different structure for her work in Swift-DocC-Render.

**Review by mayaepps — APPROVED** [review]
Looks good to me!

**Review by d-ronnqvist — APPROVED** [review]

**Comment by anferbui** [comment]
@QuietMisdreavus Are we ok to merge this PR? :shipit:

**Comment by QuietMisdreavus** [comment]
@anferbui I was hoping to get a look from @hqhhuang, since she was going to be the one that made the DocC-Render PR.

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Review by eango — APPROVED** [review]

**Comment by QuietMisdreavus** [comment]
@swift-ci Please test

**Pull request merged**
