### PR TITLE
Update version of swift-crypto to 3.0.0

### PR DESCRIPTION
**Pull request by matthewbastien**
This is tracked by rdar://139431425 as a part of swiftlang/vscode-swift#562

## Summary

Update swift-crypto to 3.0.0 to match the version used by SourceKit-LSP. This is being done so that SourceKit-LSP can use swift-docc as a dependency in order to handle convert service requests for the VS Code Swift extension.

## Dependencies

n/a

## Testing

n/a

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

~[ ] Added tests~
- [x] Ran the `./bin/test` script and it succeeded

~[ ] Updated documentation if necessary~

I did not add any tests or update the documentation as no new functionality was added. This PR only updates swift-crypto to 3.0.0.

### CODE REVIEW

**Comment by matthewbastien** [comment]
@swift-ci please test

**Comment by matthewbastien** [comment]
@swift-ci please test

**Comment by matthewbastien** [comment]
Ran a full toolchain build which completed successfully: https://github.com/swiftlang/swift/pull/77492

**Review by d-ronnqvist — APPROVED** [review]

**Comment by matthewbastien** [comment]
@swift-ci please test

**Review by franklinsch — APPROVED** [review]

**Pull request merged**
