### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kolecke**
Bug/issue #, if applicable: 

## Summary

GitHub Pages do not automatically redirect and should be updated.

### CODE REVIEW

**Review by QuietMisdreavus — APPROVED** [review]
There's some other GitHub Pages links scattered throughout our docs that also need to be updated, but this is a start.

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by d-ronnqvist** [comment]
Sorry, I didn't see this PR. I made these changes and more in https://github.com/swiftlang/swift-docc/pull/977

**Comment by d-ronnqvist** [comment]
@swift-ci please test

**Pull request merged**
